# Generated by Django 6.1.1 on 2026-10-05 19:41

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("markdown", 0),
                            ("rich_text", 1),
                            ("figure", 4),
                            ("code", 7),
                            ("quote", 8),
                        ],
                        block_lookup={
                            0: ("core.blocks.MarkdownBlock", (), {}),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "hr",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageBlock", [], {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("bash", "Shell"),
                                        ("sql", "SQL"),
                                        ("javascript", "JavaScript"),
                                        ("typescript", "TypeScript"),
                                        ("json", "JSON"),
                                        ("yaml", "YAML"),
                                        ("html", "HTML"),
                                        ("text", "Plain text"),
                                    ]
                                },
                            ),
                            6: ("wagtail.blocks.TextBlock", (), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 5), ("code", 6)]],
                                {},
                            ),
                            8: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                        },
                    ),
                ),
                ("show_in_footer", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("headline", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("show_email", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Public phone numbers attract spam; off by default.",
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Markdown. Shown at the top of the home page."
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "resume_pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "home page (resume)",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("company", models.CharField(max_length=160)),
                ("client", models.CharField(blank=True, max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave empty if current.", null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One bullet per line."),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="core.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("school", models.CharField(max_length=160)),
                ("degree", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="core.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "education",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=160)),
                ("period", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField(blank=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=80)),
                ("skills", models.TextField(help_text="Comma-separated.")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_groups",
                        to="core.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
