# Generated by Django 6.1.1 on 2026-10-05 19:41

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0098_apitoken"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="TopicIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Angle, audience, points to cover."
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("used_at"), nulls_first=True),
                    "created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Shown in lists, meta and link previews.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("markdown", 0),
                            ("rich_text", 1),
                            ("figure", 4),
                            ("code", 7),
                            ("quote", 8),
                        ],
                        block_lookup={
                            0: ("core.blocks.MarkdownBlock", (), {}),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "hr",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageBlock", [], {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("bash", "Shell"),
                                        ("sql", "SQL"),
                                        ("javascript", "JavaScript"),
                                        ("typescript", "TypeScript"),
                                        ("json", "JSON"),
                                        ("yaml", "YAML"),
                                        ("html", "HTML"),
                                        ("text", "Plain text"),
                                    ]
                                },
                            ),
                            6: ("wagtail.blocks.TextBlock", (), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 5), ("code", 6)]],
                                {},
                            ),
                            8: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                        },
                    ),
                ),
                (
                    "queue_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs review (AI draft)"),
                            ("queued", "Queued for daily publish"),
                        ],
                        default="draft",
                        help_text="Unpublished posts set to Queued go live one per day via the daily task. Use Publish to put a post live right away.",
                        max_length=20,
                        verbose_name="daily queue",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Written by me"), ("ai", "AI draft")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "publish_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="Queued posts publish on the first daily run at/after this time. Empty = next daily run.",
                        null=True,
                    ),
                ),
                ("share_to_facebook", models.BooleanField(default=True)),
                (
                    "facebook_message",
                    models.TextField(
                        blank=True,
                        help_text="Text for the Facebook post. Defaults to the excerpt.",
                    ),
                ),
                ("facebook_post_id", models.CharField(blank=True, max_length=100)),
                ("facebook_shared_at", models.DateTimeField(blank=True, null=True)),
                ("facebook_error", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="blog.blogpostpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPostTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpostpage",
            index=models.Index(
                fields=["queue_status", "publish_after"],
                name="blog_blogpo_queue_s_ffc606_idx",
            ),
        ),
    ]
