"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ
import structlog

BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

DEBUG = env.bool("DJANGO_DEBUG", default=False)
SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-build-only" if DEBUG else env.NOTSET)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])
DATABASES = {
    "default": env.db(
        "DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}" if DEBUG else env.NOTSET
    )
}  # 4 slashes = absolute, survives running manage.py from any cwd


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # Wagtail's Postgres search backend (SearchVectorField)
    "django_structlog",
    "crontask",
    "django_tailwind_cli",
    # Wagtail CMS
    "wagtail.contrib.redirects",
    "wagtail.contrib.routable_page",
    "wagtail.contrib.sitemaps",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "users",
    "core",
    "blog",
    "api",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.analytics",
                "core.context_processors.site",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Auth — django-allauth
INSTALLED_APPS += [
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.mfa",
    # "allauth.socialaccount",   # uncomment for social providers
]

MIDDLEWARE += ["allauth.account.middleware.AccountMiddleware"]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",  # must be first — wrong order silently disables lockout
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1
SITE_DOMAIN = env("DJANGO_SITE_DOMAIN", default="localhost:8000" if DEBUG else env.NOTSET)
LOGIN_REDIRECT_URL = "/"  # don't send non-staff users to /admin/
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Username-based custom user (users.User): accept either identifier at login.
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"  # tightened in production

# Brute-force lockout — django-axes
INSTALLED_APPS += ["axes"]

# AxesMiddleware MUST be the last entry — wraps every other middleware's
# auth attempts. Append so `production.py` middleware additions don't get
# dropped by re-declaring the list.
MIDDLEWARE += ["axes.middleware.AxesMiddleware"]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]
AXES_RESET_ON_SUCCESS = True
# Behind the Caddy reverse proxy in prod, REMOTE_ADDR is the proxy's IP.
AXES_IPWARE_PROXY_COUNT = env.int("AXES_IPWARE_PROXY_COUNT", default=0)
AXES_IPWARE_META_PRECEDENCE_ORDER = ["HTTP_X_FORWARDED_FOR", "REMOTE_ADDR"]

# Cache — per-process in-memory
CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

# SEO — sitemap
INSTALLED_APPS += ["django.contrib.sitemaps"]

# Absolute URL advertised to crawlers; robots.txt appends a `Sitemap:` line when set.
SITEMAP_URL = env("SITEMAP_URL", default=None)
ROBOTS_DISALLOW_ALL = env.bool("ROBOTS_DISALLOW_ALL", default=False)

# Analytics — GoatCounter (cookieless; no consent banner needed)
ANALYTICS_ID = env("ANALYTICS_ID", default="")
ANALYTICS_HOST = env("ANALYTICS_HOST", default="")

# GDPR / privacy
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
# IP addresses are personal data under GDPR — keep them out of request logs.
DJANGO_STRUCTLOG_IP_LOGGING_ENABLED = False
# Days to keep django-axes login attempts / access logs before the daily purge.
PRIVACY_LOGIN_ATTEMPT_RETENTION_DAYS = env.int("PRIVACY_LOGIN_ATTEMPT_RETENTION_DAYS", default=30)

# Blog automation — daily publish + Facebook Page share + Claude fallback drafts
BLOG_DAILY_CRON = env("BLOG_DAILY_CRON", default="0 9 * * *")  # crontab, in TIME_ZONE
FACEBOOK_PAGE_ID = env("FACEBOOK_PAGE_ID", default="")
FACEBOOK_PAGE_ACCESS_TOKEN = env("FACEBOOK_PAGE_ACCESS_TOKEN", default="")
FACEBOOK_APP_SECRET = env("FACEBOOK_APP_SECRET", default="")  # enables appsecret_proof
FACEBOOK_GRAPH_VERSION = env("FACEBOOK_GRAPH_VERSION", default="v23.0")
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default="")
BLOG_AI_FALLBACK_ENABLED = env.bool("BLOG_AI_FALLBACK_ENABLED", default=True)
BLOG_AI_AUTO_PUBLISH = env.bool("BLOG_AI_AUTO_PUBLISH", default=False)
BLOG_AI_MODEL = env("BLOG_AI_MODEL", default="claude-opus-5-5")

# Wagtail CMS — Wagtail admin at /admin/, Django admin at /django-admin/
WAGTAIL_SITE_NAME = "Nikko Comidoy"
WAGTAILADMIN_BASE_URL = f"{'http' if DEBUG else 'https'}://{SITE_DOMAIN}"
# Sign in through allauth so TOTP (allauth.mfa) and axes apply to the CMS too.
WAGTAILADMIN_LOGIN_URL = "account_login"
WAGTAILDOCS_EXTENSIONS = ["pdf"]
# Privacy: no Gravatar lookups (leaks editor emails) and no upgrade-check pings.
WAGTAIL_GRAVATAR_PROVIDER_URL = None
WAGTAIL_ENABLE_UPDATE_CHECK = False
WAGTAILSEARCH_BACKENDS = {"default": {"BACKEND": "wagtail.search.backends.database"}}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = env(
    "DJANGO_TIME_ZONE", default="America/Toronto"
)  # also drives the daily cron schedule
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Storage — S3 (django-storages)
# Gated defaults match the foundation pattern: dev/build runs zero-config,
# prod (DEBUG unset) raises ImproperlyConfigured if any of these is missing.
# Keys are optional: leave them unset on EC2 and boto3 uses the instance role
# (temporary credentials from the instance metadata service). `None`, not "" —
# an empty string makes boto3 sign requests with blank credentials.
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="") or None
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="") or None
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="" if DEBUG else env.NOTSET)
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
# Non-AWS providers (MinIO, R2, B2, Spaces): set the endpoint, skip
# AWS_S3_CUSTOM_DOMAIN so django-storages signs URLs against the endpoint.
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default="")
AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default="")

# Media to S3 when a bucket is configured; fall back to local FileSystemStorage
# when AWS_STORAGE_BUCKET_NAME is empty so a fresh `runserver` boots without creds.
# Static stays on Django's local backend in base — production.py flips it to S3.
if AWS_STORAGE_BUCKET_NAME:
    _default_storage = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {"location": "media"},
    }
else:
    _default_storage = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

STATIC_URL = "/static/"
STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)  # S3StaticStorage ignores it in prod; collectstatic needs it here
MEDIA_ROOT = BASE_DIR / "media"

# Frontend — Tailwind via django-tailwind-cli (standalone binary, no Node)
# Tailwind CLI scans templates listed via @source directives in the source CSS;
# STATICFILES_DIRS = [BASE_DIR / "assets"] is where the compiled CSS lands.
STATICFILES_DIRS = [BASE_DIR / "assets"]
TAILWIND_CLI_SRC_CSS = "tailwind-src/css/source.css"  # custom source — outside STATICFILES_DIRS  # local FileSystemStorage fallback (dev without a bucket)

# Browsers re-download every media object on every view without this.
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
# Never overwrite an upload that shares a name (Wagtail check wagtailadmin.W004);
# storages appends a suffix instead. Static files opt back in (production.py).
AWS_S3_FILE_OVERWRITE = False
# Public media URLs (bucket policy grants read on media/*): signed URLs expire, which
# breaks cached pages and Facebook link-preview images.
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None  # bucket-owner-enforced; access via bucket policy

AWS_S3_URL_PROTOCOL = env("AWS_S3_URL_PROTOCOL", default="https:")
if AWS_S3_CUSTOM_DOMAIN:
    MEDIA_URL = f"{AWS_S3_URL_PROTOCOL}//{AWS_S3_CUSTOM_DOMAIN}/media/"
else:
    MEDIA_URL = "/media/"


# Email — console in dev, SMTP (Amazon SES SMTP endpoint) in prod
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="webmaster@localhost" if DEBUG else env.NOTSET
)
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
ADMINS = [(address.split("@", 1)[0], address) for address in env.list("DJANGO_ADMINS", default=[])]

MAILERS = {
    "default": {
        "BACKEND": (
            "django.core.mail.backends.console.EmailBackend"
            if DEBUG
            else "django.core.mail.backends.smtp.EmailBackend"
        ),
        "OPTIONS": {}
        if DEBUG
        else {
            "host": env("DJANGO_MAIL_HOST", default=env.NOTSET),
            "port": env.int("DJANGO_MAIL_PORT", default=587),
            "use_tls": env.bool("DJANGO_MAIL_USE_TLS", default=True),
            "username": env("DJANGO_MAIL_USERNAME", default=""),
            "password": env("DJANGO_MAIL_PASSWORD", default=""),
            "timeout": env.int("DJANGO_MAIL_TIMEOUT", default=10),
        },
    },
}


# Logging — structlog: pretty console in dev, JSON lines in prod.
# Shared chain. Used as `foreign_pre_chain` (stdlib records) and inside
# structlog.configure() (structlog-native records). Each record runs it once.
PRE_CHAIN = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.add_log_level,
    structlog.stdlib.add_logger_name,
    structlog.processors.TimeStamper(fmt="iso", utc=True),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.format_exc_info,
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "structlog.stdlib.ProcessorFormatter",
            "processor": structlog.processors.JSONRenderer(),
            "foreign_pre_chain": PRE_CHAIN,
        },
        "console": {
            "()": "structlog.stdlib.ProcessorFormatter",
            "processor": structlog.dev.ConsoleRenderer(colors=True),
            "foreign_pre_chain": PRE_CHAIN,
        },
    },
    "filters": {
        # GDPR: never emit request bodies, auth headers, cookies or tokens.
        "drop_sensitive": {"()": "core.logging.DropSensitiveKeysFilter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console" if DEBUG else "json",
            "filters": ["drop_sensitive"],
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.db.backends": {"level": "WARNING"},
        "django.request": {"level": "WARNING"},
        "urllib3": {"level": "WARNING"},
        "botocore": {"level": "WARNING"},
        "celery": {"level": "INFO"},
    },
}

structlog.configure(
    processors=[*PRE_CHAIN, structlog.stdlib.ProcessorFormatter.wrap_for_formatter],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

try:
    import django_stubs_ext
except ImportError:
    pass  # dev-only dep; prod doesn't need it
else:
    django_stubs_ext.monkeypatch()
